___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE

import numpy as np




### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [6]:
# YOUR CODE IS HERE
my_list = [5, 10, 15, 20, 25]

np.array(my_list)




array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [7]:
# YOUR CODE IS HERE

np.zeros((5,5))



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [8]:
# YOUR CODE IS HERE
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 5. Make all the values of the array above with the value of 7.

In [9]:
# YOUR CODE IS HERE

arr = np.ones((4,4),dtype = int) * 7
arr


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [10]:
# YOUR CODE IS HERE
np.full((4,4),7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive).

In [11]:
# YOUR CODE IS HERE

np.arange(2, 17, 2)



array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [12]:
# YOUR CODE IS HERE
np.arange(0, 25).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [13]:
# YOUR CODE IS HERE
np.linspace(0,24,25, dtype = int).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [14]:
# YOUR CODE IS HERE
np.random.rand(5)


array([0.17129704, 0.85667011, 0.49017606, 0.4940206 , 0.05992815])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [15]:
# YOUR CODE IS HERE
np.random.rand(5, 5)


array([[0.96294613, 0.08593104, 0.54668858, 0.6359679 , 0.43715624],
       [0.94073136, 0.59680922, 0.65860555, 0.39121203, 0.83801805],
       [0.01519235, 0.65545746, 0.89552638, 0.03450529, 0.21892078],
       [0.83241838, 0.03864167, 0.32713814, 0.88374564, 0.05436873],
       [0.86060309, 0.02380693, 0.80148608, 0.72170469, 0.6467581 ]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [16]:
# YOUR CODE IS HERE
np.random.randint(20,50, (3, 4))



array([[28, 47, 48, 34],
       [26, 33, 29, 47],
       [33, 46, 46, 46]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [17]:
# YOUR CODE IS HERE

ranarr = np.random.randint(48, size = (1,48))
ranarr



array([[ 3, 18, 34, 16, 47, 28, 37,  6, 19,  3, 33, 22,  3, 44, 24, 28,
        12, 12, 38, 16, 23, 45,  6, 38, 26, 41, 15, 12, 31, 25, 15, 19,
         7, 20, 40, 12, 15, 12, 43, 18,  1, 40, 31, 29, 40, 24,  8, 44]])

In [18]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr.reshape(6,8)

array([[ 3, 18, 34, 16, 47, 28, 37,  6],
       [19,  3, 33, 22,  3, 44, 24, 28],
       [12, 12, 38, 16, 23, 45,  6, 38],
       [26, 41, 15, 12, 31, 25, 15, 19],
       [ 7, 20, 40, 12, 15, 12, 43, 18],
       [ 1, 40, 31, 29, 40, 24,  8, 44]])

In [19]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(-1, 8)

array([[ 3, 18, 34, 16, 47, 28, 37,  6],
       [19,  3, 33, 22,  3, 44, 24, 28],
       [12, 12, 38, 16, 23, 45,  6, 38],
       [26, 41, 15, 12, 31, 25, 15, 19],
       [ 7, 20, 40, 12, 15, 12, 43, 18],
       [ 1, 40, 31, 29, 40, 24,  8, 44]])

In [20]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(6, -1)

array([[ 3, 18, 34, 16, 47, 28, 37,  6],
       [19,  3, 33, 22,  3, 44, 24, 28],
       [12, 12, 38, 16, 23, 45,  6, 38],
       [26, 41, 15, 12, 31, 25, 15, 19],
       [ 7, 20, 40, 12, 15, 12, 43, 18],
       [ 1, 40, 31, 29, 40, 24,  8, 44]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [21]:
# YOUR CODE IS HERE

mat = np.arange(1,17).reshape(4, 4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [22]:
# YOUR CODE IS HERE
mat[1:3, 1:3]


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [23]:
# YOUR CODE IS HERE
mat[:, 0]


array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [24]:
# YOUR CODE IS HERE
mat[[1], [0,2]]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [25]:
# YOUR CODE IS HERE
mat[:, 2] = 77
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [26]:
# YOUR CODE IS HERE
mat[[1],[0,2]]


array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [27]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [28]:
# YOUR CODE IS HERE
mat[1::2, ::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [29]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [30]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat"

# YOUR CODE IS HERE
mat[mat < 10]


array([1, 2, 4, 5, 6, 8, 9])

In [31]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE
mat[mat > 12]



array([77, 77, 77, 13, 14, 77, 16])

In [32]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE

mat[mat < 10] + mat[mat > 12]

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [33]:
# YOUR CODE IS HERE
(mat[mat < 10] + mat[mat > 12]).std()


29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [34]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [35]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat"

# YOUR CODE IS HERE
mat = np.arange(1,17).reshape(4, 4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
# YOUR CODE IS HERE
np.sum(mat[:, 1])


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [37]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE

# YOUR CODE IS HERE
third_column = mat[:, 2]
third_column



array([ 3,  7, 11, 15])

In [39]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?

# YOUR CODE IS HERE
third_row = mat[2, :]
third_row


array([ 9, 10, 11, 12])

In [45]:
# LET US GET MEDIAN VALUE

# YOUR CODE IS HERE

print(np.median(third_column))
print(np.median(third_row))



9.0
10.5


In [46]:
# LET US GET MEAN VALUE

# YOUR CODE IS HERE

print(np.mean(third_column))
print(np.mean(third_row))

9.0
10.5


In [47]:
# LET US GET STANDART DEVIATION (std) VALUE

# YOUR CODE IS HERE

print(np.std(third_column))
print(np.std(third_row))



4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [27]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

[pandas.read_csv() function --> (pandas official document)](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

In [28]:
!pip install py7zr

import py7zr
with py7zr.SevenZipFile('Salaries.7z', mode='r') as z:
    z.extractall()

In [29]:
# LET US READ Salaries.csv

# YOUR CODE IS HERE

df = pd.read_csv('Salaries.csv')


In [30]:
# LET US LOOK AT THE FIRST 5 ROWS

# YOUR CODE IS HERE

df.head()



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [31]:
# LET US GET A SAMPLE

# YOUR CODE IS HERE

df.sample(1)



Id     EmployeeName      JobTitle   BasePay  OvertimePay  \
131517  131518  Grace M Espinal  Senior Clerk  63269.01       990.64   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
131517   1433.39  27918.48  65693.04          93611.52  2014    NaN   

               Agency  Status  
131517  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [32]:
# YOUR CODE IS HERE

df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [33]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

# YOUR CODE IS HERE

df.describe()



Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [34]:
# YOUR CODE IS HERE

df['Year'].value_counts()



Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: count, dtype: int64

In [35]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE

df['Year'].nunique()


4

In [36]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE
df['Year'].unique()


array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [37]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE

df['TotalPay'].max()



567595.43

In [38]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE

df['TotalPay'].mean()



74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [39]:
# YOUR CODE IS HERE
df[df['TotalPay'] > df['TotalPay'].mean()] 



Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [40]:
# YOUR CODE IS HERE

df[df['TotalPay'] > df['TotalPay'].mean()].shape[0] 




69489

### How much does ALBERT PARDINI make money (including benefits)?

In [41]:
# YOUR CODE IS HERE

df[df['EmployeeName'] == 'ALBERT PARDINI']['TotalPayBenefits']



2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [42]:
pd.Series(df.loc[df['TotalPayBenefits'].idxmin(), 'EmployeeName'], index=[df['TotalPayBenefits'].idxmin()] )

148653    Joe Lopez
dtype: object

### What are the unique Jobs in dataset?

In [43]:
# YOUR CODE IS HERE

df['JobTitle'].unique()



array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [44]:
# YOUR CODE IS HERE
df['JobTitle'].value_counts().tail(3)



JobTitle
COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: count, dtype: int64

### How many people earned more than avg in 2012?

In [45]:
data_2012 = df[df['Year'] == 2012]
data_2012


Id        EmployeeName                      JobTitle    BasePay  \
36159  36160      Gary Altenberg  Lieutenant, Fire Suppression  128808.87   
36160  36161        Gregory Suhr               Chief of Police  302578.00   
36161  36162          Khoa Trinh   Electronic Maintenance Tech  111921.00   
36162  36163  Joanne Hayes-White        Chief, Fire Department  296943.01   
36163  36164   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19   
...      ...                 ...                           ...        ...   
72920  72921    Charles Williams                  Junior Clerk     -30.58   
72921  72922        John Carajan               General Laborer       0.00   
72922  72923         John Draper                         Clerk      -9.50   
72923  72924        Cherise Wong                 Special Nurse       0.00   
72924  72925        Donald Clark              Transit Operator       0.00   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160         0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161    146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162         0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163    192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...            ...       ...       ...        ...               ...   ...   
72920        45.87      0.00      1.36      15.29             16.65  2012   
72921         0.00      0.00     12.90       0.00             12.90  2012   
72922        14.25      0.00      0.42       4.75              5.17  2012   
72923         0.00      3.28      0.88       3.28              4.16  2012   
72924         0.00      1.77      0.14       1.77              1.91  2012   

       Notes         Agency  Status  
36159    NaN  San Francisco     NaN  
36160    NaN  San Francisco     NaN  
36161    NaN  San Francisco     NaN  
36162    NaN  San Francisco     NaN  
36163    NaN  San Francisco     NaN  
...      ...            ...     ...  
72920    NaN  San Francisco     NaN  
72921    NaN  San Francisco     NaN  
72922    NaN  San Francisco     NaN  
72923    NaN  San Francisco     NaN  
72924    NaN  San Francisco     NaN  

[36766 rows x 13 columns]

In [70]:
avg_2012 = data_2012['TotalPayBenefits'].mean()
avg_2012

100553.22923244302

In [72]:
data_2012[data_2012['TotalPayBenefits'] > avg_2012]

Id         EmployeeName                        JobTitle    BasePay  \
36159  36160       Gary Altenberg    Lieutenant, Fire Suppression  128808.87   
36160  36161         Gregory Suhr                 Chief of Police  302578.00   
36161  36162           Khoa Trinh     Electronic Maintenance Tech  111921.00   
36162  36163   Joanne Hayes-White          Chief, Fire Department  296943.01   
36163  36164    Frederick Binkley       EMT/Paramedic/Firefighter  126863.19   
...      ...                  ...                             ...        ...   
54857  54858       Wanda Williams                Transit Operator   57219.28   
54858  54859       Adriana Touhey  Central Processing & Dist Tech   66882.02   
54859  54860         Maria Porras                Transit Operator   53356.22   
54860  54861  Tewolde Weldetensae              Survey Assistant I   68913.01   
54861  54862         Marisa Ramos           Executive Secretary 1   67519.73   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160         0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161    146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162         0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163    192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...            ...       ...       ...        ...               ...   ...   
54857      8358.60   1362.29  33632.35   66940.17         100572.52  2012   
54858      2023.39    824.00  30842.27   69729.41         100571.68  2012   
54859     16048.06    402.93  30761.25   69807.21         100568.46  2012   
54860       306.61      0.00  31343.15   69219.62         100562.77  2012   
54861       919.82    624.01  31499.18   69063.56         100562.74  2012   

       Notes         Agency  Status  
36159    NaN  San Francisco     NaN  
36160    NaN  San Francisco     NaN  
36161    NaN  San Francisco     NaN  
36162    NaN  San Francisco     NaN  
36163    NaN  San Francisco     NaN  
...      ...            ...     ...  
54857    NaN  San Francisco     NaN  
54858    NaN  San Francisco     NaN  
54859    NaN  San Francisco     NaN  
54860    NaN  San Francisco     NaN  
54861    NaN  San Francisco     NaN  

[18703 rows x 13 columns]

In [71]:
earned_more_avg = data_2012[data_2012['TotalPayBenefits'] > avg_2012].shape[0]
earned_more_avg

18703

### How many people have a title of Manager in their jobs?

In [48]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE

df['JobTitle'].apply(lambda x: 'Manager' in x).sum()


3080

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [49]:
# YOUR CODE IS HERE
sal_new = df.iloc[:, [0, 1, 2, 7, 8]]
sal_new


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [50]:
# YOUR CODE IS HERE
df.loc[:, 'EmployeeName':'TotalPayBenefits']


EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [58]:
earn_min = df['TotalPayBenefits'].min()
earn_min

-618.13

In [60]:
earn_avg = df['TotalPayBenefits'].mean()
earn_avg

93692.55481056681

In [65]:
earn_list = df[(df['TotalPayBenefits'] > earn_min) & (df['TotalPayBenefits'] < earn_avg)]
earn_list

Id    EmployeeName             JobTitle   BasePay  OvertimePay  \
10806    10807         KWE LEE  AUTOMOTIVE MECHANIC  72198.10      6017.76   
10807    10808  MIGUEL CARO JR  STATIONARY ENGINEER  72420.69      2665.79   
10808    10809   JOANNE MORRIS     REGISTERED NURSE  91672.69         0.00   
10809    10810   LAYLA WELBORN        SPECIAL NURSE  80683.54      8809.03   
10810    10811         LE BANH     TRANSIT OPERATOR  67349.30     23507.62   
...        ...             ...                  ...       ...          ...   
148648  148649     Leon Walker            Custodian      0.00         0.00   
148649  148650   Roy I Tillery            Custodian      0.00         0.00   
148650  148651    Not provided         Not provided       NaN          NaN   
148651  148652    Not provided         Not provided       NaN          NaN   
148652  148653    Not provided         Not provided       NaN          NaN   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
10806   15475.29       NaN  93691.15          93691.15  2011    NaN   
10807   18596.26       NaN  93682.74          93682.74  2011    NaN   
10808    2007.84       NaN  93680.53          93680.53  2011    NaN   
10809    4184.31       NaN  93676.88          93676.88  2011    NaN   
10810    2818.47       NaN  93675.39          93675.39  2011    NaN   
...          ...       ...       ...               ...   ...    ...   
148648      0.00       0.0      0.00              0.00  2014    NaN   
148649      0.00       0.0      0.00              0.00  2014    NaN   
148650       NaN       NaN      0.00              0.00  2014    NaN   
148651       NaN       NaN      0.00              0.00  2014    NaN   
148652       NaN       NaN      0.00              0.00  2014    NaN   

               Agency  Status  
10806   San Francisco     NaN  
10807   San Francisco     NaN  
10808   San Francisco     NaN  
10809   San Francisco     NaN  
10810   San Francisco     NaN  
...               ...     ...  
148648  San Francisco     NaN  
148649  San Francisco     NaN  
148650  San Francisco     NaN  
148651  San Francisco     NaN  
148652  San Francisco     NaN  

[75649 rows x 13 columns]

In [69]:
# YOUR CODE IS HERE
employee_list = earn_list[['EmployeeName', 'TotalPayBenefits']]
employee_list



EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________