___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [5]:
# YOUR CODE IS HERE

import numpy as np




### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [6]:
# YOUR CODE IS HERE
my_list = [5, 10, 15, 20, 25]

np.array(my_list)




array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [7]:
# YOUR CODE IS HERE

np.zeros((5,5))



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [8]:
# YOUR CODE IS HERE
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 5. Make all the values of the array above with the value of 7.

In [9]:
# YOUR CODE IS HERE

arr = np.ones((4,4),dtype = int) * 7
arr


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [10]:
# YOUR CODE IS HERE
np.full((4,4),7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive).

In [11]:
# YOUR CODE IS HERE

np.arange(2, 17, 2)



array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [12]:
# YOUR CODE IS HERE
np.arange(0, 25).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [13]:
# YOUR CODE IS HERE
np.linspace(0,24,25, dtype = int).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [14]:
# YOUR CODE IS HERE
np.random.rand(5)


array([0.17129704, 0.85667011, 0.49017606, 0.4940206 , 0.05992815])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [15]:
# YOUR CODE IS HERE
np.random.rand(5, 5)


array([[0.96294613, 0.08593104, 0.54668858, 0.6359679 , 0.43715624],
       [0.94073136, 0.59680922, 0.65860555, 0.39121203, 0.83801805],
       [0.01519235, 0.65545746, 0.89552638, 0.03450529, 0.21892078],
       [0.83241838, 0.03864167, 0.32713814, 0.88374564, 0.05436873],
       [0.86060309, 0.02380693, 0.80148608, 0.72170469, 0.6467581 ]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [16]:
# YOUR CODE IS HERE
np.random.randint(20,50, (3, 4))



array([[28, 47, 48, 34],
       [26, 33, 29, 47],
       [33, 46, 46, 46]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [17]:
# YOUR CODE IS HERE

ranarr = np.random.randint(48, size = (1,48))
ranarr



array([[ 3, 18, 34, 16, 47, 28, 37,  6, 19,  3, 33, 22,  3, 44, 24, 28,
        12, 12, 38, 16, 23, 45,  6, 38, 26, 41, 15, 12, 31, 25, 15, 19,
         7, 20, 40, 12, 15, 12, 43, 18,  1, 40, 31, 29, 40, 24,  8, 44]])

In [18]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr.reshape(6,8)

array([[ 3, 18, 34, 16, 47, 28, 37,  6],
       [19,  3, 33, 22,  3, 44, 24, 28],
       [12, 12, 38, 16, 23, 45,  6, 38],
       [26, 41, 15, 12, 31, 25, 15, 19],
       [ 7, 20, 40, 12, 15, 12, 43, 18],
       [ 1, 40, 31, 29, 40, 24,  8, 44]])

In [19]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(-1, 8)

array([[ 3, 18, 34, 16, 47, 28, 37,  6],
       [19,  3, 33, 22,  3, 44, 24, 28],
       [12, 12, 38, 16, 23, 45,  6, 38],
       [26, 41, 15, 12, 31, 25, 15, 19],
       [ 7, 20, 40, 12, 15, 12, 43, 18],
       [ 1, 40, 31, 29, 40, 24,  8, 44]])

In [20]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(6, -1)

array([[ 3, 18, 34, 16, 47, 28, 37,  6],
       [19,  3, 33, 22,  3, 44, 24, 28],
       [12, 12, 38, 16, 23, 45,  6, 38],
       [26, 41, 15, 12, 31, 25, 15, 19],
       [ 7, 20, 40, 12, 15, 12, 43, 18],
       [ 1, 40, 31, 29, 40, 24,  8, 44]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [21]:
# YOUR CODE IS HERE

mat = np.arange(1,17).reshape(4, 4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [22]:
# YOUR CODE IS HERE
mat[1:3, 1:3]


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [23]:
# YOUR CODE IS HERE
mat[:, 0]


array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [24]:
# YOUR CODE IS HERE
mat[[1], [0,2]]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [25]:
# YOUR CODE IS HERE
mat[:, 2] = 77
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [26]:
# YOUR CODE IS HERE
mat[[1],[0,2]]


array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [27]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [28]:
# YOUR CODE IS HERE
mat[1::2, ::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [29]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [30]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat"

# YOUR CODE IS HERE
mat[mat < 10]


array([1, 2, 4, 5, 6, 8, 9])

In [31]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE
mat[mat > 12]



array([77, 77, 77, 13, 14, 77, 16])

In [32]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE

mat[mat < 10] + mat[mat > 12]

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [33]:
# YOUR CODE IS HERE
(mat[mat < 10] + mat[mat > 12]).std()


29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [34]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [35]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat"

# YOUR CODE IS HERE
mat = np.arange(1,17).reshape(4, 4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
# YOUR CODE IS HERE
np.sum(mat[:, 1])


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [37]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE

# YOUR CODE IS HERE
third_column = mat[:, 2]
third_column



array([ 3,  7, 11, 15])

In [39]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?

# YOUR CODE IS HERE
third_row = mat[2, :]
third_row


array([ 9, 10, 11, 12])

In [45]:
# LET US GET MEDIAN VALUE

# YOUR CODE IS HERE

print(np.median(third_column))
print(np.median(third_row))



9.0
10.5


In [46]:
# LET US GET MEAN VALUE

# YOUR CODE IS HERE

print(np.mean(third_column))
print(np.mean(third_row))

9.0
10.5


In [47]:
# LET US GET STANDART DEVIATION (std) VALUE

# YOUR CODE IS HERE

print(np.std(third_column))
print(np.std(third_row))



4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [1]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

[pandas.read_csv() function --> (pandas official document)](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

In [2]:
!pip install py7zr

import py7zr
with py7zr.SevenZipFile('Salaries.7z', mode='r') as z:
    z.extractall()

In [ ]:
# LET US READ Salaries.csv

# YOUR CODE IS HERE



In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS

# YOUR CODE IS HERE



Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE

# YOUR CODE IS HERE



Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE



In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

# YOUR CODE IS HERE



Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE



In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE



In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE



### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE



In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE



### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE



Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE



### How much does ALBERT PARDINI make money (including benefits)?

In [ ]:
# YOUR CODE IS HERE



### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE



### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE



### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE



### How many people earned more than avg in 2012?

In [ ]:
# YOUR CODE IS HERE



### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________